export default [
  {
    menuId: 1,
    parentId: 0,
    name: 'システム',
    url: null,
    perms: null,
    type: 0,
    level: '0',
    icon: 'i-system',
    componentName: null,
    toChildUrl: null,
    orderNum: 99,
    children: [
      {
        menuId: 39,
        parentId: 1,
        name: '随時処理',
        url: 'sys/anytime',
        perms: null,
        type: 0,
        level: '0.1',
        icon: null,
        componentName: null,
        toChildUrl: '/sys/anytime/batch',
        orderNum: 0,
        children: [
          {
            menuId: 68,
            parentId: 39,
            name: 'ホーム',
            url: 'sys/anytime/home',
            perms: 'sys:anytime:home:list',
            type: 1,
            level: '0.1.39',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 70,
            actions: 'list'
          },
          {
            menuId: 67,
            parentId: 39,
            name: '月间勤务状况',
            url: 'sys/anytime/month',
            perms: 'sys:anytime:month:list',
            type: 1,
            level: '0.1.39',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 71,
            actions: 'list'
          },
          {
            menuId: 70,
            parentId: 39,
            name: '日别勤务状况',
            url: 'sys/anytime/day',
            perms: 'sys:anytime:day:list',
            type: 1,
            level: '0.1.39',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 72,
            actions: 'list'
          },
          {
            menuId: 65,
            parentId: 39,
            name: '休暇申請',
            url: 'sys/anytime/apply',
            perms: 'sys:anytime:apply:list',
            type: 1,
            level: '0.1.39',
            icon: 'i-apply',
            componentName: null,
            toChildUrl: null,
            orderNum: 73,
            actions: 'list'
          },
          {
            menuId: 71,
            parentId: 39,
            name: '超过勤务状况',
            url: 'sys/anytime/over',
            perms: 'sys:anytime:over:list',
            type: 1,
            level: '0.1.39',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 80,
            actions: 'list'
          },
          {
            menuId: 48,
            parentId: 39,
            name: 'バッチ処理',
            url: 'sys/anytime/batch',
            perms: 'sys:anytime:batch:list',
            type: 1,
            level: '0.1.39',
            icon: 'i-batch',
            componentName: null,
            toChildUrl: null,
            orderNum: 98,
            actions: 'happybatch:applybatch:list:deptbatch'
          },
          {
            menuId: 40,
            parentId: 39,
            name: 'セッティング',
            url: 'sys/anytime/profile',
            perms: 'sys:anytime:profile:list',
            type: 1,
            level: '0.1.39',
            icon: 'i-profile',
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'infoUpdate:list:customize:passwordUpdate'
          },
          {
            menuId: 69,
            parentId: 39,
            name: '打刻履历',
            url: 'sys/anytime/stamp',
            perms: 'sys:anytime:stamp:list',
            type: 1,
            level: '0.1.39',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'list'
          }
        ]
      },
      {
        menuId: 72,
        parentId: 1,
        name: '日報',
        url: 'sys/dailyReporter',
        perms: null,
        type: 0,
        level: '0.1',
        icon: null,
        componentName: null,
        toChildUrl: '/sys/dailyReporter/setting',
        orderNum: 6,
        children: [
          {
            menuId: 73,
            parentId: 72,
            name: 'project登録',
            url: 'sys/dailyreporter/setting',
            perms: 'sys:dailyreporter:setting:list',
            type: 1,
            level: '0.1.72',
            icon: null,
            componentName: null,
            toChildUrl: 'sys/dailyReporter/setting',
            orderNum: 70,
            actions: 'list'
          },
          {
            menuId: 74,
            parentId: 72,
            name: '日报一览',
            url: 'sys/dailyreporter/reporter',
            perms: 'sys:dailyreporter:reporter:list',
            type: 1,
            level: '0.1.72',
            icon: null,
            componentName: null,
            toChildUrl: 'sys/dailyReporter/setting',
            orderNum: 71,
            actions: 'list'
          }
        ]
      },
      {
        menuId: 2,
        parentId: 1,
        name: '有休管理',
        url: null,
        perms: null,
        type: 0,
        level: '0.1',
        icon: 'i-vacation',
        componentName: null,
        toChildUrl: '/sys/vacation/view',
        orderNum: 99,
        children: [
          {
            menuId: 16,
            parentId: 2,
            name: '有休設定管理',
            url: 'sys/vacation/mode',
            perms: 'sys:vacation:mode:list',
            type: 1,
            level: '0.1.2',
            icon: 'i-vacation-mode',
            componentName: null,
            toChildUrl: null,
            orderNum: 81,
            actions: 'save:list'
          },
          {
            menuId: 17,
            parentId: 2,
            name: '有休取得一覧',
            url: 'sys/vacation/view',
            perms: 'sys:vacation:view:list',
            type: 1,
            level: '0.1.2',
            icon: 'i-vacation-view',
            componentName: null,
            toChildUrl: null,
            orderNum: 88,
            actions: 'list'
          },
          {
            menuId: 53,
            parentId: 2,
            name: '休暇申請設定',
            url: 'sys/vacation/config',
            perms: 'sys:vacation:config:list',
            type: 1,
            level: '0.1.2',
            icon: 'i-rest-config',
            componentName: null,
            toChildUrl: null,
            orderNum: 91,
            actions: 'update:list:delete:add'
          },
          {
            menuId: 78,
            parentId: 2,
            name: '特休取得条件管理',
            url: 'sys/vacation/special',
            perms: 'sys:vacation:special:list',
            type: 1,
            level: '0.1.2',
            icon: null,
            componentName: null,
            toChildUrl: 'sys/month/confirm',
            orderNum: 99,
            actions: 'list'
          }
        ]
      },
      {
        menuId: 3,
        parentId: 1,
        name: 'マスタ登録',
        url: null,
        perms: null,
        type: 0,
        level: '0.1',
        icon: 'i-master',
        componentName: null,
        toChildUrl: '/sys/master/user',
        orderNum: 99,
        children: [
          {
            menuId: 10,
            parentId: 3,
            name: '権限管理',
            url: 'sys/master/role',
            perms: 'sys:master:role:list',
            type: 1,
            level: '0.1.3',
            icon: 'i-role',
            componentName: null,
            toChildUrl: null,
            orderNum: 78,
            actions: 'list:update:delete:save'
          },
          {
            menuId: 8,
            parentId: 3,
            name: '所属管理',
            url: 'sys/master/dept',
            perms: 'sys:master:dept:list',
            type: 1,
            level: '0.1.3',
            icon: 'i-dept',
            componentName: null,
            toChildUrl: null,
            orderNum: 79,
            actions: 'list'
          },
          {
            menuId: 7,
            parentId: 3,
            name: 'アカウント管理',
            url: 'sys/master/user',
            perms: 'sys:master:user:list',
            type: 1,
            level: '0.1.3',
            icon: 'i-user',
            componentName: null,
            toChildUrl: null,
            orderNum: 80,
            actions: 'save:list:update:delete'
          },
          {
            menuId: 11,
            parentId: 3,
            name: '社員管理',
            url: 'sys/master/emp',
            perms: 'sys:master:emp:list',
            type: 1,
            level: '0.1.3',
            icon: 'i-employ',
            componentName: null,
            toChildUrl: null,
            orderNum: 81,
            actions: 'list:delete:save:update'
          },
          {
            menuId: 79,
            parentId: 3,
            name: '職員区分登録',
            url: 'sys/master/usertype',
            perms: 'sys:master:usertype:list',
            type: 1,
            level: '0.1.3',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 82,
            actions: 'list:delete:add:update'
          },
          {
            menuId: 81,
            parentId: 3,
            name: '勤务体系登录',
            url: 'sys/master/workpattern',
            perms: 'sys:master:workpattern:list',
            type: 1,
            level: '0.1.3',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 83,
            actions: 'list'
          },
          {
            menuId: 80,
            parentId: 3,
            name: '勤怠对象外社员登录',
            url: 'sys/master/superuser',
            perms: 'sys:master:superuser:list',
            type: 1,
            level: '0.1.3',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 84,
            actions: 'list'
          },
          {
            menuId: 82,
            parentId: 3,
            name: '祝日登録',
            url: 'sys/master/happyday',
            perms: 'sys:master:happyday:list',
            type: 1,
            level: '0.1.3',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 85,
            actions: 'list:add:delete:update'
          },
          {
            menuId: 83,
            parentId: 3,
            name: '端末登陆',
            url: 'sys/master/machine',
            perms: 'sys:master:machine:list',
            type: 1,
            level: '0.1.3',
            icon: null,
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'list:add:delete:update'
          }
        ]
      },
      {
        menuId: 4,
        parentId: 1,
        name: 'システム',
        url: null,
        perms: null,
        type: 0,
        level: '0.1',
        icon: 'i-settings',
        componentName: null,
        toChildUrl: '/sys/settings/menu',
        orderNum: 99,
        children: [
          {
            menuId: 14,
            parentId: 4,
            name: '操作ログ',
            url: 'sys/settings/operation',
            perms: 'sys:settings:operation:list',
            type: 1,
            level: '0.1.4',
            icon: 'i-operation-log',
            componentName: null,
            toChildUrl: null,
            orderNum: 92,
            actions: 'list'
          },
          {
            menuId: 15,
            parentId: 4,
            name: 'エラーログ',
            url: 'sys/settings/error',
            perms: 'sys:settings:error:list',
            type: 1,
            level: '0.1.4',
            icon: 'i-error-log',
            componentName: null,
            toChildUrl: null,
            orderNum: 93,
            actions: 'list'
          },
          {
            menuId: 6,
            parentId: 4,
            name: 'メニュー管理',
            url: 'sys/settings/menu',
            perms: 'sys:settings:menu:list',
            type: 1,
            level: '0.1.4',
            icon: 'i-menu',
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'list'
          },
          {
            menuId: 9,
            parentId: 4,
            name: 'セッティング',
            url: 'sys/settings/config',
            perms: 'sys:settings:config:list',
            type: 1,
            level: '0.1.4',
            icon: 'i-config',
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'list'
          },
          {
            menuId: 12,
            parentId: 4,
            name: 'ログインログ',
            url: 'sys/settings/login',
            perms: 'sys:settings:login:list',
            type: 1,
            level: '0.1.4',
            icon: 'i-login-log',
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'list'
          },
          {
            menuId: 13,
            parentId: 4,
            name: 'アクセスログ',
            url: 'sys/settings/access',
            perms: 'sys:settings:access:list',
            type: 1,
            level: '0.1.4',
            icon: 'i-access-log',
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'list'
          }
        ]
      },
      {
        menuId: 5,
        parentId: 1,
        name: '申請・承認',
        url: null,
        perms: null,
        type: 0,
        level: '0.1',
        icon: 'i-apply',
        componentName: null,
        toChildUrl: '/sys/apply/state',
        orderNum: 99,
        children: [
          {
            menuId: 64,
            parentId: 5,
            name: '申請承認',
            url: 'sys/apply/confirm',
            perms: 'sys:apply:confirm:list',
            type: 1,
            level: '0.1.5',
            icon: 'i-apply-confirm',
            componentName: null,
            toChildUrl: null,
            orderNum: 98,
            actions: 'list'
          },
          {
            menuId: 18,
            parentId: 5,
            name: '申請状況一覧',
            url: 'sys/apply/state',
            perms: 'sys:apply:state:list',
            type: 1,
            level: '0.1.5',
            icon: 'i-apply-record',
            componentName: null,
            toChildUrl: null,
            orderNum: 99,
            actions: 'list'
          }
        ]
      },
      {
        menuId: 75,
        parentId: 1,
        name: '月次处理',
        url: 'sys/month',
        perms: null,
        type: 0,
        level: '0.1',
        icon: null,
        componentName: null,
        toChildUrl: '/sys/month/confirm',
        orderNum: 99,
        children: [
          {
            menuId: 76,
            parentId: 75,
            name: '月结',
            url: 'sys/month/confirm',
            perms: 'sys:month:confirm:list',
            type: 1,
            level: '0.1.75',
            icon: null,
            componentName: null,
            toChildUrl: 'sys/month/confirm',
            orderNum: 99,
            actions: 'list'
          },
          {
            menuId: 77,
            parentId: 75,
            name: '张票出力',
            url: 'sys/month/output',
            perms: 'sys:month:output:list',
            type: 1,
            level: '0.1.75',
            icon: null,
            componentName: null,
            toChildUrl: 'sys/month/confirm',
            orderNum: 99,
            actions: 'list'
          }
        ]
      }
    ]
  }
]
